[package]
name = "bevy_declarative_ui"
version = "0.1.0"
edition = "2024"

[features]
dynamic = ["dynamic_ui"]


[dependencies]
bevy = "0.16.1"
dyn-clone = "1.0.19"
bevy_declarative_ui_parser = {path = "../bevy_declarative_ui_parser" }
dynamic_ui = { path = "../dynamic_ui", optional = true }