[package]
name = "bevy_declarative_ui_parser"
version = "0.1.0"
edition = "2024"

[features]
node_span = []

[dependencies]
thiserror.workspace = true
regex.workspace = true
rayon.workspace = true
log.workspace = true
